"""initial schema

Revision ID: 86c6ed1d84b1
Revises: 97e6b79e076a
Create Date: 2026-06-09 03:16:37.332866

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "86c6ed1d84b1"
down_revision: Union[str, None] = "97e6b79e076a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
