"""initial schema

Revision ID: c2d3890cf0b7
Revises: 86c6ed1d84b1
Create Date: 2026-06-09 03:21:16.458967

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c2d3890cf0b7"
down_revision: Union[str, None] = "86c6ed1d84b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
