import * as React from "react";
import Link from "next/link";
import { ArrowLeft, FileText, CheckCircle2 } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — SigmaSec",
  description: "Terms governing the use of the SigmaSec security posture intelligence and autonomous remediation platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#07090e] text-slate-200 antialiased">
      {/* Top Header Navigation */}
      <header className="border-b border-slate-800 bg-[#07090e]/90 backdrop-blur sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-xs font-mono text-slate-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" /> Back to Home
          </Link>
          <div className="flex items-center gap-2">
            <span className="font-bold text-sm tracking-tight text-white">SigmaSec</span>
            <span className="text-[10px] font-mono text-cyan-400 bg-cyan-950/60 border border-cyan-800/60 px-2 py-0.5 rounded">
              LEGAL TERMS
            </span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <div className="mb-10">
          <span className="text-xs font-mono text-cyan-400 tracking-wider uppercase font-semibold">
            Evaluation &amp; Commercial Agreement
          </span>
          <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight mt-2">
            Terms of Service
          </h1>
          <p className="text-slate-400 text-sm font-mono mt-2">
            Last Updated: September 2026 · Beta &amp; Pilot Release
          </p>
        </div>

        <article className="space-y-8 text-sm leading-relaxed text-slate-300">
          <section className="border-t border-slate-800 pt-6">
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-cyan-400 font-mono text-xs">01</span> Platform Services
            </h2>
            <p className="mb-2">
              SigmaSec provides automated vulnerability discovery, AST call-graph reachability analysis, threat intelligence correlation (CISA KEV, EPSS), sandbox exploit validation, and autonomous remediation generation services.
            </p>
            <p>
              By accessing our platform or requesting pilot onboarding, you agree to comply with these terms.
            </p>
          </section>

          <section className="border-t border-slate-800 pt-6">
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-cyan-400 font-mono text-xs">02</span> Authorized Use &amp; Scanning Scope
            </h2>
            <p className="mb-3">
              You warrant that you own or have explicit authorization to scan, analyze, and test all code repositories, cloud assets, container registries, network hosts, and endpoints configured in your SigmaSec account.
            </p>
            <p>
              Using SigmaSec to test third-party assets without verified authorization is strictly prohibited.
            </p>
          </section>

          <section className="border-t border-slate-800 pt-6">
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-cyan-400 font-mono text-xs">03</span> Intellectual Property &amp; Generated Code
            </h2>
            <p className="mb-2">
              <strong>Your Data:</strong> You retain complete and exclusive ownership of all source code, container images, scan configurations, and finding telemetry.
            </p>
            <p>
              <strong>Remediation PRs:</strong> All patch diffs, pull requests, and remediation scripts generated by SigmaSec for your repositories become your exclusive property upon creation.
            </p>
          </section>

          <section className="border-t border-slate-800 pt-6">
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-cyan-400 font-mono text-xs">04</span> Service Level &amp; Pilot Disclaimer
            </h2>
            <p>
              During evaluation and beta pilot periods, the platform is provided on an &quot;as-is&quot; basis. While SigmaSec executes rigorous AST reachability verification and sandbox validations, engineering teams must review all auto-generated pull requests before merging into production environments.
            </p>
          </section>

          <section className="border-t border-slate-800 pt-6">
            <h2 className="text-lg font-bold text-white mb-3 flex items-center gap-2">
              <span className="text-cyan-400 font-mono text-xs">05</span> Questions &amp; Support
            </h2>
            <p className="text-slate-400">
              For commercial agreements, custom master service agreements (MSAs), or legal questions, email{" "}
              <a href="mailto:legal@sigmasec.ai" className="text-cyan-400 hover:underline">
                legal@sigmasec.ai
              </a>.
            </p>
          </section>
        </article>
      </main>
    </div>
  );
}
